spring:
  profiles:
    active: docker
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://identity-service:8081
          predicates:
            - Path=/api/auth/**
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: task-service
          uri: http://task-service:8082
          predicates:
            - Path=/api/tasks/**
          filters:
            - StripPrefix=1
            - name: JwtAuthFilter
  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret-file: /run/secrets/jwt_secret.txt

identity-service:
  url: ${IDENTITY_SERVICE_URL:http://identity-service:8081}

task-service:
  url: ${TASK_SERVICE_URL:http://task-service:8082}
