spring:
  data:
    redis:
      host: localhost
      port: 6379

identity-service:
  url: ${IDENTITY_SERVICE_URL:http://localhost:8081}

task-service:
  url: ${TASK_SERVICE_URL:http://localhost:8082}