spring:
  application:
    name: task-service
  profiles:
    active: docker

  datasource:
    #url: jdbc:postgresql://postgres:5432/taskdb  # Needed when running using docker
    url: jdbc:postgresql://localhost:5432/taskdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: ${DTH_JWT_SECRET}
  accessTokenExpiryMs: 900000       # 15 minutes
  refreshTokenExpiryMs: 604800000   # 7 days

logging:
  level:
    root: INFO
    com.deeptechhub.taskservice: DEBUG
  file:
    name: logs/task-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

identity-service:
  url: ${IDENTITY_SERVICE_URL:http://localhost:8081} # The identity service URL

# Feign specific config
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

